--GPU
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'GPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'GPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'GPU');
--

--CPU
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'CPU'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'CPU'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'CPU');
--


-- MAINBOARD
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MAINBOARD'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MAINBOARD'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MAINBOARD');
--



--MEMORY
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'MEMORY'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'MEMORY'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'MEMORY');
--




--STORAGE
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'STORAGE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'STORAGE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'STORAGE');
--


--POWER
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'POWER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'POWER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'POWER');
--


--COOLER
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COOLER'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COOLER'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COOLER');
--


--COMPUTERCASE
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
INSERT INTO posts (NAME, VENDOR, PART) VALUES ('이엠텍 지포스 RTX 3050 STORM X NANO D6 6GB', '이엠텍', 'COMPUTERCASE'), ('COLORFUL iGAME 지포스 RTX 5080 ULTRA OC White D7 16GB 웨이코스', 'CORORFUL iGAME', 'COMPUTERCASE'), ('ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB', 'ZOTAC GAMING', 'COMPUTERCASE');
--



